### ISSUE TITLE
Unable to generate theme - Android Studio 0.3.2

### ISSUE THREAD

**Issue by sohailalam2** [jeromevdl/android-holo-colors-idea-plugin#2]
The plugin tries to download stuffs but finally fails with the following message:

"Unable to generate your theme, please go to http://android-holo-colors.com"

I am using Android Studio 0.3.2 with JRE 1.7

**Comment by or-shahaf** [comment]
Still having this issue.
Android Studio 1.4
JRE: 1.8.0_60
Windows 10 64b
Apparently Holo Colors Genrator's version is still 1.0, so thats no surprise.

**Comment by jason-allen-oneal** [comment]
Same issue on AS 2.3
