### ISSUE TITLE
doesn't work in AS 2.3

### ISSUE THREAD

**Issue by jason-allen-oneal** [jeromevdl/android-holo-colors-idea-plugin#8]
I get cannot generate your theme, visit blah blah, but the site is down, too.

**Comment by AlexandraMariaPistol** [comment]
Doesn't work for me neither. Have you managed to find a way to generate you theme? I really need it

**Comment by jason-allen-oneal** [comment]
No luck at all.

**Comment by voghDev** [comment]
If you guys need the plugin that much, you might consider [making a donation](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XQSBX55A2Z46U)

All the effort for developing such tool + hosting on the internet costs money, you know ;-)

**Comment by jeromevdl** [comment]
The website is now closed. Holo is deprecated, you should have a look a material design.
